### ISSUE TITLE
--auto-liquidity error

### ISSUE THREAD

**Issue by tipogi** [ACINQ/phoenixd#31]
I have been playing with the service (testnet) and I got an error  when I want to make bigger the channel. It might be that I am using wrong or something missing but I am facing that error log: **Address in use**. This is my channel info:

```json
{
    "nodeId": "xxxx",
    "channels": [
        {
            "state": "Normal",
            "channelId": "xxxxx",
            "balanceSat": 30125,
            "inboundLiquiditySat": 1985760,
            "capacitySat": 2017474,
            "fundingTxId": "f21e83ef3deddc1678633af78cf06df4584ff4f4e7ca6a343f6efe4c00257fe0"
        }
    ],
    "chain": "testnet",
    "version": "0.1.4-SNAPSHOT-75247e4"
}
```

and the error log

```bash
223d06015dd5:~/bin$ ./phoenixd --auto-liquidity=5m
2024-04-10 05:43:35 datadir: /phoenix/.phoenix
2024-04-10 05:43:35 chain: Testnet
2024-04-10 05:43:35 autoLiquidity: 5000000 sat
2024-04-10 05:43:35 nodeid: xxxxxxx
2024-04-10 05:43:36 connecting to lightning peer...
2024-04-10 05:43:37 connected to lightning peer
Exception in thread "DefaultDispatcher-worker-9" java.net.BindException: Address in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at io.ktor.network.sockets.ConnectUtilsJvmKt.bind(ConnectUtilsJvm.kt:35)
	at io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:45)
	at io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:29)
	at io.ktor.server.cio.backend.HttpServerKt$httpServer$acceptJob$1.invokeSuspend(HttpServer.kt:48)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [LazyStandaloneCoroutine{Cancelling}@450345ec, Dispatchers.IO]
2024-04-10 05:43:37 http server stopped
2024-04-10 05:43:40 disconnected from lightning peer
2024-04-10 05:43:43 connecting to lightning peer...
2024-04-10 05:43:43 connected to lightning peer
2024-04-10 05:43:46 disconnected from lightning peer
2024-04-10 05:43:49 connecting to lightning peer...
2024-04-10 05:43:49 connected to lightning peer
2024-04-10 05:43:52 disconnected from lightning peer
```

**Comment by pm47** [comment]
It's unrelated to the liquidity parameter. You have another instance of phoenixd running (or another app using the same http port) and need to kill it first.

**Comment by tipogi** [comment]
Ok that make sense! I was running that command inside of the docker container while the container was running that service...

**Comment by tipogi** [comment]
Ok that make sense! I was running that command inside of the docker container while the container was running that service...
